title: Jett's Insight
author: Jett
email: kwj0326@gmail.com
description: >-
  경제, IT, 사회의 흐름을 날카롭게 예측하고 분석합니다.
url: "https://jett-1993.github.io"
baseurl: "/blog"
theme: minima
timezone: Asia/Seoul
future: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
